export catArray = [
    'Abyssinian',
    'Aegean',
    'American Bobtail',
    'American Curl',
    'American Ringtail',
    'American Shorthair',
    'American Wirehair',
    'Aphrodite Giant',
    'Arabian Mau',
    'Asian cat',
    'Asian Semi-longhair',
    'Australian Mist',
    'Balinese',
    'Bambino',
    'Bengal',
    'Birman',
    'Bombay',
    'Brazilian Shorthair',
    'British Longhair',
    'British Shorthair',
    'Burmese',
    'Burmilla',
    'California Spangled',
    'Chantilly-Tiffany',
    'Chartreux',
    'Chausie',
    'Colorpoint Shorthair',
    'Cornish Rex',
    'Cymric',
    'Manx Longhair',
    'Long-haired Manx',
    'Cyprus',
    'Devon Rex',
    'Donskoy',
    'Don Sphynx',
    'Dragon Li',
    'Chinese Li Hua',
    'Dwelf',
    'Egyptian Mau',
    'European Shorthair',
    'Exotic Shorthair',
    'Foldex',
    'German Rex',
    'Havana Brown',
    'Highlander',
    'Himalayan',
    'Colorpoint Persian',
    'Japanese Bobtail',
    'Javanese',
    'Colorpoint Longhair',
    'Kanaani',
    'Khao Manee',
    'Kinkalow',
    'Korat',
    'Korean Bobtail',
    'Korn Ja',
    'Kurilian Bobtail',
    'Kuril Islands Bobtail',
    'Lambkin',
    'LaPerm',
    'Lykoi',
    'Maine Coon',
    'Manx',
    'Mekong Bobtail',
    'Minskin',
    'Napoleon',
    'Munchkin',
    'Nebelung',
    'Norwegian Forest Cat',
    'Ocicat',
    'Ojos Azules',
    'Oregon Rex',
    'Oriental Bicolor',
    'Oriental Longhair',
    'Oriental Shorthair',
    'Persian',
    'Peterbald',
    'Pixie-bob',
    'Ragamuffin',
    'Ragdoll',
    'Raas',
    'Russian Blue',
    'Russian White',
    'Russian Black',
    'Russian Tabby',
    'Sam Sawet',
    'Savannah',
    'Scottish Fold',
    'Selkirk Rex',
    'Serengeti',
    'Serrade Petit',
    'Siamese',
    'Siberian',
    'Siberian Forest Cat',
    'Neva Masquerade',
    'Singapura',
    'Snowshoe',
    'Sokoke',
    'Somali',
    'Sphynx',
    'Suphalak',
    'Thai',
    'Wichien Maat',
    'Thai Lilac',
    'Thai Blue Point',
    'Thai Lilac Point',
    'Tonkinese',
    'Toyger',
    'Turkish Angora',
    'Turkish Van',
    'Turkish Vankedisi',
    'Ukrainian Levkoy',
    'Wila Krungthep',
    'York Chocolate'
    ];